/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 molot.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

function ModelMolot(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/molot.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    if (actions && Object.keys(actions).length > 0) {
      const animationName = 'ArmatureAction';
      const action = actions.ArmatureAction

      // Запускаем анимацию
      action.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-0.015, -7.17, -1.998]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone001} />
          <primitive object={nodes.Bone002} />
          <primitive object={nodes.Bone003} />
          <primitive object={nodes.neutral_bone} />
          <mesh name="BézierCircle" geometry={nodes.BézierCircle.geometry} material={nodes.BézierCircle.material} position={[0.551, 1.36, 6.301]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0.015, 0.171, 7.543]} />
          <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[0.015, 5.201, -0.164]} />
          <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[0.015, 5.634, -0.125]} />
          <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[0.015, 0.046, -1.279]} />
          <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[0.771, 1.421, 0.592]} rotation={[0, 0, 0.081]} />
          <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[0.604, 1.611, 0.903]} rotation={[1.522, 1.562, -1.744]} />
          <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[0.015, 0.714, -0.18]} />
          <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-0.03, 0.943, 7.523]} rotation={[0, 0, -Math.PI / 2]} />
            <skinnedMesh name="BézierCircle001" geometry={nodes.BézierCircle001.geometry} material={nodes.BézierCircle001.material} skeleton={nodes.BézierCircle001.skeleton} />
          <skinnedMesh name="Circle" geometry={nodes.Circle.geometry} material={nodes.Circle.material} skeleton={nodes.Circle.skeleton} />
          <skinnedMesh name="Circle001" geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} skeleton={nodes.Circle001.skeleton} />
          <skinnedMesh name="Circle002" geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} skeleton={nodes.Circle002.skeleton} />
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} skeleton={nodes.Cube.skeleton} />
          <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} skeleton={nodes.Cube001.skeleton} />
          <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} skeleton={nodes.Cube002.skeleton} />
          <skinnedMesh name="Cube003" geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} skeleton={nodes.Cube003.skeleton} />
          <skinnedMesh name="Cube007" geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} skeleton={nodes.Cube007.skeleton} />
          <skinnedMesh name="Cube014" geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} skeleton={nodes.Cube014.skeleton} />
          <skinnedMesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} skeleton={nodes.Cylinder.skeleton} />
          <skinnedMesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} skeleton={nodes.Cylinder001.skeleton} />
          <skinnedMesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} skeleton={nodes.Cylinder002.skeleton} />
          <skinnedMesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} skeleton={nodes.Cylinder003.skeleton} />
          <skinnedMesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} skeleton={nodes.Cylinder004.skeleton} />
          <skinnedMesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} skeleton={nodes.Cylinder006.skeleton} />
          <skinnedMesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} skeleton={nodes.Cylinder007.skeleton} />
          <skinnedMesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} skeleton={nodes.Cylinder008.skeleton} />
          <skinnedMesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} skeleton={nodes.Plane.skeleton} />
          <skinnedMesh name="Plane001" geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} skeleton={nodes.Plane001.skeleton} />
        </group>
      </group>
    </group>

  )
}

export default ModelMolot

useGLTF.preload('/models/molot.glb')
