/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vishka.glb --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Vishka(props) {
  const { nodes, materials } = useGLTF('/models/vishka.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0.009, -6.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-3.008, -2.14, 3.027]} />
      <mesh castShadow receiveShadow geometry={nodes.Circle_cell010.geometry} material={nodes.Circle_cell010.material} position={[0.004, -0.302, -0.106]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[0, -16.57, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[0, -24.869, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[0, -14.673, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0, -12.385, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[0, -16.25, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0, -13.107, 0.709]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[3.027, -2.14, 3.027]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[5.067, -4.928, -2.324]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-4.538, -3.817, 1.47]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-4.538, -3.817, -1.098]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[0, -26.716, 0]} />
    </group>
  )
}

export default Vishka
useGLTF.preload('/models/vishka.glb')
