import Header from "@/components/Header";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="ru">
            <body>
                <div className="cont">
                    <div className="wrapper">
                        <Header />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
